version: '3'
services:
  server:
    build: ./servidor
    ports:
      - "4444:4444"
    volumes:
      - /tmp/javadir:/tmp/javadir
  server2:
    build: ./servidor
    ports:
      - "4443:4444"
    volumes:
      - /tmp/javadir:/tmp/javadir
 