version: '3'
services:
  server:
    build: ./servidor
    ports:
      - "4444:4444"
    volumes:
      - /home/soporte/logs:/tmp/javadir
    environment:
      - nombre=Servidor 1
      - logName=logfile1
      - port=4444